/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

*/


let fibSum = 0;
let fibNum = [];
let fibTemp = 0;


for (let i = 0;
  (fibTemp < 4000000); i++) {
  if ((i == 0) || (i == 1)) {
    fibTemp = 1;
    fibNum.push(fibTemp);
  }
  else {
    fibTemp = (fibNum[i - 1] + fibNum[i - 2]);
    fibNum.push(fibTemp);
  }
  if ((fibTemp % 2) == 0) {
    fibSum += fibTemp
  }
  console.log(`Term: ${i} \t FibNum: ${fibTemp}\t FibSum: ${fibSum}`)
}
